### ISSUE TITLE
Stickers on owned jokers should update when winning a run

### ISSUE THREAD

**Issue by Ardub23** [SirMaiquis/Balatro-Stickers-Always-Shown#2]
When you win a run and proceed to endless mode, it would be nice to see the new stake sticker applied immediately. Instead it only updates after returning to the menu and then continuing the run.

**Comment by SirMaiquis** [comment]
Thank you for bringing this to my attention. I have implemented a fix that ensures the new stake sticker is applied immediately upon entering endless mode after winning a run. You no longer need to return to the menu for the sticker to update.

This change has been included in the latest release. Please update to version 1.2.2 of the mod to benefit from this improvement.

If you encounter any further issues or have additional suggestions, feel free to let me know.
